### ISSUE TITLE
Colons in the code

### ISSUE THREAD

**Issue by giddyhup** [zero-udo/eurotronic-cometblue#1]
I would have loved to use this but it seems there are several issues. There are colons all over the code which do not make much sense (e.g. in CometBlueTests.py: 'result: dict = blue.get_weekday(Weekday.FRIDAY)'),  

I had to change requirements.txt to 'pygatt[GATTTOOL]==4.0.5' for the setup  to work.

**Comment by zero-udo** [comment]
Interesting. Setup worked for me, but if it increases compatibility I changed it to the uppercase variant.

Those colons are variable annotations described in PEP 526. I wasn't aware that they are this "new" (introduced in Python 3.6) as this is my first Python project - requirements and pypi classifiers are changed accordingly.

**Comment by giddyhup** [comment]
Thank you for your reaction. I hadn't come across this kind of variable annotation before. It explains why with Python 3.5 it wasn't working. The gatttool line in requirements was also missing a T, perhaps lower caps would have worked with the additional letter.

Anyway, thank you for your work. I'll update my python version now.

**Comment by giddyhup** [comment]
@zero-udo - I installed it successfully under python 3.8.6. pexpect (and perhaps its dependency ptyprocess) should be added to the requirements.
